test version 0.4.7

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -41,21 +41,36 @@ jobs:
     - name: make scripts executable
       run: chmod +x ./packages/mapo-webapp-deploy/publish-actions.sh ./packages/mapo-webapp-deploy/deploy-actions.sh
     
-    # Get the commit hash
-    - name: shorten the commit hash
-      id: vars
-      run: |
-        calculatedSha=$(git rev-parse --short ${{ github.sha }})
-        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
+    # # Get the commit hash
+    # - name: shorten the commit hash
+    #   id: vars
+    #   run: |
+    #     calculatedSha=$(git rev-parse --short ${{ github.sha }})
+    #     echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
     
-    # Check to make sure the commit hash is correct
-    - name: confirm the commit hash
-      run: echo ${{ env.COMMIT_SHORT_SHA }}
+    # # Check to make sure the commit hash is correct
+    # - name: confirm the commit hash
+    #   run: echo ${{ env.COMMIT_SHORT_SHA }}
+
+    
+    # Extract the tag in commit message
+    - name: extract the version in commit message
+      id: extracted_version
+      run: |
+        VERSION=$(git log -1 --pretty=%B | grep -oP 'version (\S+)' | awk '{print $2}')
+
+        if [ -z "$VERSION" ]; then
+          echo "ERROR, no version found"
+          exit 1
+        fi
+        
+        echo "VERSION=$VERSION" >> $GITHUB_ENV
+        echo "Version set to $VERSION"
 
     # Build and publish docker image
     - name: build and publish the docker image
-      run: ./packages/mapo-webapp-deploy/publish-actions.sh ${{ env.COMMIT_SHORT_SHA }}
+      run: ./packages/mapo-webapp-deploy/publish-actions.sh ${{ env.VERSION }}
       
     # Deploy to dev
     - name: deploy to dev VM
-      run: ./packages/mapo-webapp-deploy/deploy-actions.sh dev ${{ env.COMMIT_SHORT_SHA }}
+      run: ./packages/mapo-webapp-deploy/deploy-actions.sh dev ${{ env.VERSION }}
